teaxyz/www

- index.html
This proposed change is for accessibility purposes. A screen reader has no idea `ofc` stands for of course. You all don't have a CONTRIBUTE.md setup yet so I hope I'm not breaking any laws here by doing this 😅.
> Expands ofc to be "Of course"

- .markdownlint.json
- LICENSE.md
- README.md
- public/index.html
This is pretty optional, but did some formatting cleanup while auditing referenced files. The bulk of it is reindenting index.html (thank you, VSCode).
Signed-off-by: Jacob Heider <jacob@tea.xyz>
> some cleanup during audit

- public/index.html
- public/style.css
@jhheider Added needed content to landing page for authenticated users. Put script instructions in style.css; toggling displays and editing inner html. Lmk if you have any questions. Listed classes and id's.
> Content for authenticated users; script directions

- public/white-paper/index.html
Added some styling to enable scrolling on mobile.
> mobile scrolling fix

- public/white-paper/index.html
Added GitHub icon; adjusted menu for tablet view on /white-paper/. 
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1202296055612620
> Tom small changes

- public/index.html
- public/white-paper/index.html
Changed color of Linktree link to teal
> Changed linktree link to teal

- public/index.html
- public/white-paper/index.html
- Expanded the breakpoint in which the mobile white paper module appears. 
- Made a font size chaneg to Github icon as well.
> Issue #29 (Fix Tablet Not Being Detected As Mobile)

- public/404.html
- public/index.html
- public/white-paper/index.html
Added Gypsy GA tags to home, whitepaper, and 404. As per instructions in <head> and just after opening <body>. @mxcl  if you would prefer to place the tags elsewhere for performance, let me know. 
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1202324715895733
> Add google analytics gypsy

- public/404.html
- public/index.html
- public/white-paper/index.html
- Added FB pixel tag to <head> (both pages)
- Updated email subscribe to submit to Sendx instead of Mailchimp (both pages) 
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1202324715895729
> Additions from tom

- public/404.html
- public/index.html
- public/white-paper/index.html
Changed the dataLayer name for Gypsy dataLayer to prevent it competing with internal tea tag.
> Potential fix for Gypsy GTM tag

- public/404.html
- public/index.html
- public/white-paper/index.html
@Xercesblu3 as discussed in meeting. If this doesn't work, one other consideration might be that the codes have been shared in Slack/Asana--so perhaps a character was autocorrected and thus not feeding through. But hopefully this is the solution.
> Deleted old tracking code as per meeting with Gypsy--OK'd by Tim.

- public/404.html
- public/index.html
- public/white-paper/index.html
Hopefully this is a simpler fix. @Xercesblu3 Gypsy should be able to test using the staging env.
fixes #39
> Use single-quotes

- public/index.html
> use counter with total included

- layouts/partials/footer.html
@Xercesblu3 Clarity Tag Installed.
> Clarity Tag Installed for integration with Microsoft Clarity (augments our analytics)

- src/layouts/index.html
Implemented new copy from Nick--the purpose of which is to communicate the type of person whom tea is looking to authenticate.
> Github-friendly copy changes--courtesy of Nick.

- src/layouts/partials/head.html
Tag installation requested by Gypsy to verify Facebook Business Manager profile. Added to <head> partial.
> Added meta tag for Facebook biz manager verification-Gypsy request

- src/content/careers.md
- src/layouts/page/careers.html
- src/layouts/partials/footer.html
- src/layouts/partials/head.html
- src/static/css/style.css
@Xercesblu3 this PR is meant to replace #46. This PR is limited to only essential changes related to the addition of the a careers page. HTML file, corresponding Markdown file, menu updates (main & footer), CSS for the accordion component.
> Careers (html & md); menu update (main & footer); css for accordion

- src/content/terms-of-use.md
- src/layouts/page/terms-of-use.html
Terms of use page (html and markdown). Styling issues (ul and a color) resolved in PR #54
> Terms of Use Page (html + md)

- src/layouts/partials/footer.html
Added terms of use to menu footer.
> Added "Terms of Use" to menu footer

- src/layouts/page/careers.html
- Moved repeat copy (first paragraph of job descriptions atop accordion)
- Accordion now defaults to be collapsed
- Show first few lines of description to make it clear that there are multiple positions open
- Fixed a border radius issue with collapsed accordion button
> #55 - Clearly Show Multiple Roles Desired Careers Page

- src/layouts/page/careers.html
JS was impacting text based on .auth-btn class. This has been deleted.
> Deleted class that JS was impacting

- src/layouts/index.html
- src/layouts/partials/header.html
> Changed styling, text... AMA -> Discord. Removed styling rules.

- src/static/css/style.css
Not mission-critical, but was playing around with the background color for the site and think that going darker adds a little more "pop" and contrast. We can scrap this PR if the collective is not a fan, but curious to hear thoughts.
> Background color change; darker/more contrast.

- src/layouts/index.html
- src/layouts/page/tea-qr.html
- src/layouts/page/white-paper.html
- src/layouts/partials/footer.html
- src/layouts/partials/header.html
- src/layouts/partials/navbar.html
This should fix the issue of re-authentication. Specifically, if they've installed the app already, they won't just be stranded, and our site's auth will work across browsers and sessions.
> Auth instead of install for the buttons

- src/layouts/page/keep-what-is-yours.html
Added IDs to buttons on new landing page to make Google Tag Manager setup easier.
> Specified IDs for two buttons to make GTM setup easier

- src/layouts/page/pioneer-a-better-internet.html
Changed link for auth btn on second landing page option.
> LP Pioneer Page - Link Fix

- src/layouts/index.html
Top-commentary scroll (WIP), desktop for the time being. Need to re-format for mobile and tablet so that the cards don't stack. This section is hidden on tablet/mobile.
> (Desktop only--for now) Top commentary carousel

- src/layouts/index.html
Auth no. was going to get catty-wompus upon reaching 5 figures on mobile (last digit was going to fall to second line). Updated font-size and line height on mobile.
Photo of what would have happened: 
Photos of fix in both localStorage modes:
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1202799627891869
> Mobile counter font resize

- src/layouts/partials/footer.html
- src/layouts/partials/head.html
Installed Reddit tag on site, along with tracking code. This is currently a WIP until approval by Jayden. 
Documentation provided by Jayden: https://redditinc.force.com/helpcenter/s/article/Install-the-Reddit-Pixel-on-your-website#GTM
> Reddit tag

- .cdk/bin/app.ts
- .cdk/lib/tea.xyz.ts
- .cdk/package.json
- .cdk/yarn.lock
> Update to CDKv2

- src/layouts/index.html
Gypsy request--wanted email subscribe form added to the hero section of the home page in addition to the one that has been added to /keep-what-is-yours/ via [this PR](https://github.com/teaxyz/www/pull/83).
> Add email subscribe to homepage

- src/layouts/index.html
Fixed Discord button width wonkiness on smaller mobile devices.
> Discord button fix

- src/layouts/partials/footer.html
Fixed the width in the footer subscribe field at desktop breakpoint
> Footer subscribe form fix

- src/layouts/page/keep-what-is-yours.html
Simple text change in subhead on landing page 1 ( /keep-what-is-yours/ ) to reflect the 10,000 authenticated devs milestone.
> Text change to reflect 10k authenticated (Gypsy request)

- src/layouts/_default/baseof.html
- src/layouts/partials/head.html
Installing Stackoverflow tag at the request of Gypsy.
> Stackoverflow tag integration

- src/layouts/page/careers.html
@Xercesblu3 added Full Stack Developer to accordion and updated links/content accordingly. Let me know what you think. Leah should probably get eyes on this as well.
> Add full stack developer

- lychee.toml
- src/layouts/page/white-paper.html
@Xercesblu3 Opening up this draft PR for the translation links. Added a dropdown menu on /white-paper/ to start.
(Subordinate to https://github.com/teaxyz/white-paper/pull/77)
> WIP: Add translation links

- src/layouts/index.html
- src/layouts/page/keep-what-is-yours.html
- src/layouts/partials/footer.html
- src/layouts/partials/head.html
- src/layouts/partials/klaviyo-form.html
@Xercesblu3 this is the embedded Klaviyo form requested by Gypsy. Note: this is not the email page related to[ this issue](https://github.com/teaxyz/www/issues/105)... just replacing the existing forms on the home page, the footer, and /keep-what-is-yours/
> Klaviyo integration

- src/layouts/partials/head.html
Added new description for Google to <head>.
> Updated meta description for Google search

- src/layouts/page/white-paper.html
Requires: https://github.com/teaxyz/white-paper/pull/85
> Add DE translation

- src/layouts/page/white-paper.html
can merge with https://github.com/teaxyz/white-paper/pull/92
> add white-paper_ZH

- src/layouts/page/authentication-success.html
> Spelling fix on authentication success page

- lambdas/src/libs/airtable.ts
- lambdas/src/libs/types.ts
- src/data/packages.json
- src/layouts/partials/package-thumbnail.html
> add sorting data to generated packages.json

- src/layouts/page/white-paper.html
move initialization of dropdown/selection for languages with the adobe script tag
> fix: language selection on whitepaper page

- lambdas/package.json
- lambdas/serverless.ts
- lambdas/src/functions/ipfsUpload/handler.ts
- lambdas/src/functions/ipfsUpload/index.ts
- lambdas/src/functions/ipfsUpload/mock.json
- lambdas/yarn.lock
* just a reimplementation of the the decentralizer repo
* just added more filtering depending on which "suffix" may trigger this fn
> TS implementation: upload packages to ipfs

- lychee.toml
- src/layouts/index.html
- src/layouts/page/careers.html
- src/layouts/page/package-detail.html
- src/layouts/page/products.html
- src/layouts/page/style-guide.html
- src/layouts/partials/floating-join-btn.html
- src/layouts/partials/footer-nav.html
- src/layouts/partials/footer.html
- src/layouts/partials/klaviyo-form.html
- src/layouts/partials/white-paper-gen-art.html
- src/static/css/accordion.css
- src/static/css/footer.css
- src/static/css/homepage.css
- src/static/css/products.css
- src/static/css/typography.css
Final push before company review
> Tom block of progress

- lambdas/serverless.ts
* implemented subnet and security group to sls
> devops: vpc setup for serverless lambdas

- .github/prepare-thumb-images.sh
- .github/workflows/cd.yml
- .github/workflows/staging.yml
- src/data/packages.json
Objective: reduce cdk upload size because it fails
> WIP:  package thumbnail should come from cdn

- src/layouts/page/lisbon.html
Adjusted spacing in bottom section, spelling correction in table
> Minor spacing adjustment/spelling

- src/content/nebraska-man.md
- src/layouts/page/nebraska-man.html
- src/static/css/animations.css
- src/static/css/text-flicker.css
- Fixed spelling of 'Nebraska' in navbar
- Commented out Galaxy Eco/NFT stuff
- Commented out Flicker Effect on H1 Headers
> Day before revisions

- src/layouts/partials/footer.html
Updated counter to reflect 11:45 instead of 11:30
> :30 ==> :45

- src/layouts/partials/klaviyo-form.html
Fixed Klaviyo form in footer. Changes made to klaviyo-form partial.
> Fixed footer subscribe form

- src/layouts/index.html
- src/static/css/homepage.css
Removed Galaxy Eco logo from #partners section.
> Remove Galaxy.eco logo

- src/layouts/page/authentication-success.html
Fixed auth success page on mobile
> thanks for authenticating page fix

- src/content/press.md
- src/layouts/page/press.html
Request from Gypsy. 
- Added /press/ page to top-level menu 
- Additional styling for /press page
- Added press releases that Gypsy requested to publish
*Note: Should confirm that it's okay to publicize our brand guide
> Add press page

- src/layouts/partials/floating-join-btn.html
- src/layouts/partials/klaviyo-form.html
- src/static/css/homepage.css
Changes as follows: 
- No max width above 1792px... scales up infinitely
- Adjusted form font size on mobile
- Adjusted z-index for floating button (was getting hidden behind elements at smaller breakpoints)
> Small Design Fixes

- src/content/subscribed.md
- src/layouts/page/products.html
- src/layouts/page/subscribed.html
- src/static/css/products.css
Added subscription confirmed page --> can be viewed at /subscribed/
> Add subscription confirmed page

- src/layouts/page/nebraska-man.html
- src/layouts/partials/nebraska-man-001.html
detects if user is using mobile device, then just renders the images as a scrollable content
> #177 Nebraska-Man strip show scrollable view on mobile device

- lychee.toml
- src/layouts/partials/head.html
'tea.xyz is a feature-rich, delightful unified package manager that will revolutionize open-source development'
> Changed OG text to what Marc provided

- src/layouts/partials/package-grid.html
@getneil added some styling for the search field. Couldn't access the 'x' that appears when you start typing, but if we could change that to the grid gray (#949494), that'd be great.
> styling for fuzzy filter input

- .github/workflows/staging.yml
- lychee.toml
- src/layouts/index.html
- src/layouts/partials/footer.html
- src/layouts/partials/package-grid.html
- src/layouts/partials/package-thumbnail.html
- src/layouts/partials/search-menu.html
- src/layouts/partials/sort-dropdown.html
- src/layouts/partials/swiper.html
resolves https://github.com/teaxyz/www/issues/184
DEMO: 
- DESKTOP: https://www.loom.com/share/8e5b44c0858c4d91aec30eacc742c291
- MOBILE: https://www.loom.com/share/9f920ff4a60b44b68ac776b94990cf41
> Fuzzy filter packages

- src/layouts/page/white-paper.html
resolves https://github.com/teaxyz/www/issues/104
> +linkableWhitePapers

- src/layouts/partials/clipboard-copy.html
Changed click-to-copy value to 'sh <(curl https://tea.xyz)'
> sh <(curl https://tea.xyz) > sh <(curl tea.xyz)

- src/layouts/page/white-paper.html
'auth-btn' class was impacting the post-authenticated button state on white paper page.
> Removed 'auth-btn' classes from button on whitepaper paper page

- src/layouts/page/careers.html
Blank accordion items from Breezy data
> Careers Page Fix - Blank Accordion Items

- src/layouts/page/package-detail.html
- src/layouts/partials/clipboard-copy-package-detail.html
- src/layouts/partials/clipboard-copy.html
This PR resolves [this issue](https://github.com/teaxyz/www/issues/202).
> Don't display, but copy,  'https' from one-liner

- .github/build-package-pages.sh
- .github/workflows/staging.yml
- src/layouts/partials/package-thumbnail.html
[Hugo has a bug on capitalized page/md.](https://github.com/gohugoio/hugo/issues/7686)
we became aware of this because of the ff package: github.com/rhash/RHash
> #215 lowercase all package links

- src/layouts/page/careers.html
Second job listing was not appearing.
> Career Listing Fix

- src/layouts/page/careers.html
> Career listing

- src/layouts/index.html
@sanchitram1 this closes [this ticket](https://github.com/teaxyz/www/issues/137), let me know what you think. Open to additional suggestions to better clarify what we're showing here.
> Title/Description Change for Statistics

- lychee.toml
- src/layouts/partials/footer.html
LGTM. Here's a quick way to test it in staging: drop the following into your console:
```javascript
const signups = (500000).toLocaleString()
const res = { repos: 100000, maintainers: 200000 }
$('#count1').html(signups)
$('#count2').html(signups)
$('#count3').html(signups)
$('#count4').html(signups)
$('#count5').html(signups)
$('#count6').html(signups)
$('#count7').html(signups)
$('#stat-one').html(res.repos ? res.repos.toLocaleString() : "")
$('#stat-two').html(res.maintainers ? res.maintainers.toLocaleString() : "")
```
> fetch stats from server

- src/layouts/partials/auth-data-snippet.html
- src/layouts/partials/footer.html
- src/layouts/partials/head.html
Stats take a bit of time to load, this PR is intended to remedy that/mediate the impact to UX.
> Stats Load Speed

- src/layouts/page/press.html
- Added section to /press/ for guidelines download
- Added PDF to static
- Changed file-size indicator on /press/
> Upload Brand Guidelines

- .design/README.md
Added the necessary content to make us eligible for open-sourcing design work through [contribute.design](contribute.design). This closes issue #212
> Add Design Folder & README for Contribute.design

- src/content/careers.md
- src/content/email-subscribe.md
- src/content/media-kit.md
- src/content/nebraska-man.md
- src/content/package-manager.md
- src/content/press.md
- src/content/privacy-policy.md
- src/content/products.md
- src/content/tea-cli.md
- src/content/terms-of-use.md
- src/content/white-paper.md
This pull request closes issue #210
> Pages Have Individual Titles

- lychee.toml
- src/layouts/index.html
- src/layouts/partials/no-results-found.html
- src/layouts/partials/package-grid.html
Merging this will close[ #237 ](https://github.com/teaxyz/www/issues/237)
- Add partial that says 'no results found' (no-results-found.html)
- Show aforementioned partial if no results
- Hide 'show more' button if no results
> 'No Results Found' for Package Section

- src/layouts/partials/clipboard-copy.html
Added a 'view source' link to the right of the 'copy' button in the main click-to-copy field. Merging this PR will close #240 and #220.
> Add view source link to main click-to-copy field

- lychee.toml
- src/assets/scripts/package-bottles.jsx
- src/layouts/page/package-detail.html
- src/layouts/partials/package-bottle.html
> #232 package bottle info in the /+packagePage

- lychee.toml
- src/config.toml
- src/content/nebraska-man.md
- src/content/press.md
- src/content/white-paper.md
- src/layouts/index.html
- src/layouts/partials/footer-nav.html
- src/layouts/partials/footer.html
- src/layouts/partials/head.html
- src/layouts/partials/navbar.html
Max's comments from #www in Slack. Merging this PR will close issue #248
> Max hit list

- lychee.toml
- src/layouts/page/careers.html
Remove last accordion item in careers page.
> Remove accordion item

- src/layouts/partials/footer.html
This closes issue #262 .... made copyright date current year.
> copyright date is current year

- src/layouts/partials/footer.html
- src/layouts/partials/head.html
- src/layouts/partials/navbar.html
Changed format of stargazers number to be 0.0k format and added the GitHub release version number to the right of the stargazers number in both locations (navbar/masthead & footer social links). Merging this PR will close issue #260.
> 0.0k Format for Stargazers + Release Version Display

- src/layouts/index.html
- src/layouts/partials/head.html
Removed authentication CTA's, as well as floating 'authenticate' button.
> Remove Auth CTA's

- src/content/_index.md
- src/layouts/index.html
- src/layouts/partials/footer.html
- src/layouts/partials/head.html
- src/layouts/partials/mobile-art-home.html
- src/static/css/homepage.css
- src/static/css/typography.css
Tagline update:
- page title for index
- H1 on homepage
- footer title
- head
Updated font-size and line-height across media queries to match the grid system.
> Tagline update

- src/layouts/index.html
Commented out pre-loaded on home page.
> Remove Site Preloader

- src/layouts/page/careers.html
> Accordion update

- src/layouts/index.html
Link white paper on homepage to PDF download.
> White paper links to PDF download

- src/layouts/page/white-paper.html
Vertically centered content, commented out dropdown, changed button links
> White paper quick fix

- src/layouts/partials/header.html
- src/layouts/partials/navbar.html
> GitHUb link is just logo icon and number: <i/> (9.9K)

- src/layouts/index.html
**Before:** fetched only from `cli` and `pantry.extra`
**After:** fetches from all repos, sans `gui` as is private
> Contributors section includes all repos

- src/layouts/index.html
- src/layouts/partials/animation-3.html
- src/layouts/partials/desktop-ctas.html
- src/layouts/partials/footer-content.html
- src/layouts/partials/footer.html
- src/layouts/partials/header.html
- src/layouts/partials/navbar.html
- Parenthesis fade in as well around star count
- Added non-breaking space to tea script example
- Added Discord icon to masthead
- Updated Discord link
- Use caching and consolidate scripts to limit API requests
- Add min-width to stargazers in navbar so that the content does not 'jump'
> A series of small fixes

- src/layouts/partials/footer-content.html
Klaviyo form is not coming through, hiding for now and will figure out this weekend
> klaviyo form not coming through, hiding for now

- src/layouts/partials/clipboard-copy-package-detail.html
> Instructions Need 'sh' Appended

- src/layouts/partials/package-grid.html
- src/layouts/partials/package-thumbnail.html
> #294 improve search exact match

- src/layouts/index.html
- src/layouts/partials/footer-content.html
Fixed form in site footer, as well as added an authentication section back in below the stats section.
> Footer Form Fix & Auth Section Add

- src/layouts/partials/footer-content.html
> Fixed email form

- src/layouts/partials/footer-content.html
- text color not black anymore
- changed highlight color to be on-brand
> Small email tweaks

- src/config.toml
- src/layouts/partials/desktop-ctas.html
- src/layouts/partials/head.html
Added some stuff to push users towards Product Hunt campaign
> Added some Product Hunt stuff

- src/layouts/index.html
Made it so the banner is fixed, but can also be closed.
> Made banner closable and fixed

- src/layouts/page/gui.html
> Changed classes on gui download buttons

- src/layouts/index.html
- src/layouts/partials/click-to-copy.html
Added 'two ways to install tea' to the homepage/hero section.
https://www.loom.com/share/0e76417f3d3c4f599dbdd143d649a935
> two ways to install tea

- src/layouts/page/careers.html
Adding some error handling to the careers page, so that if no jobs are available in Breezy, the user is notified and is presented with alternative options.
> Add a 'no jobs available' if no jobs in breezy.

- src/layouts/index.html
- src/layouts/partials/click-to-copy.html
- src/layouts/partials/tea-two-ways.html
Duplicated the split CTA section (GUI/one-liner) to the other place on the page that we had a CTA.
> Duplicated CTA Section

- src/layouts/partials/click-to-copy.html
- src/layouts/partials/tea-two-ways.html
- Fixed highlight color
- Increased font-size and line height
- Brightened color
- Fixed weith of copy button
- Added mention about `brew install`
> Alt Install Methods Fix

- src/layouts/partials/package-grid.html
resolves #322
this also replicates the search in the gui
> implement Fuse index use for search

- src/layouts/partials/package-grid.html
- src/layouts/partials/search-menu.html
Amended JS to display the total number of packages. It currently shows up in the placeholder, so the text will say 'Search [x] Packages'.
> Display Number of Packages

- src/layouts/partials/auth-data-snippet.html
- src/layouts/partials/footer-content.html
- src/layouts/partials/footer.html
Forgot about logic that showed users their auth number posy-authentication. Removed said logic so that it only shows the total number of authenticated developers.
> No LocalSorage Logic for Auth Number

- src/layouts/page/authentication-success.html
Updated content to be more on par with current initiatives.
> Copy change on auth success page

- .github/get-packages-data.js
- .github/workflows/cd.yml
- .github/workflows/staging.yml
- src/layouts/partials/package-thumbnail.html
- use images that are auto-generated from SD
- use long and short descriptions
> get data from app.tea.xyz/v1/packages

- src/layouts/partials/head.html
Removing floating product badge
> Remove product hunt badge

- src/layouts/partials/head.html
Adding buy/sell script to <head> of website on Dan's request
> Add buy/sell script to <head>

- src/layouts/page/gui.html
> Fix: typos

- src/config.toml
- src/content/_index.md
- src/content/blog/_index.md
- src/content/gui.md
Google links were being camel-cased. Restructuring front-matter and config file a bit.
> Fix meta casing

- src/layouts/_default/single.html
Removed social share share buttons on blog as were distracting.
> remove social share buttons on blog

- src/layouts/partials/active-campaign-form.html
- src/layouts/partials/footer-content.html
- src/static/css/homepage.css
Replaced Klaviyo form with Active Campaign form
> active campaign form
